language: php

env:
    global:
        - CHECK_PHP_SYNTAX="no"

matrix:
    fast_finish: true
    include:
        - php: 7.0
          env: CHECK_PHP_SYNTAX="yes"
        - php: 5.6
        - php: hhvm
    allow_failures:
        - php: hhvm

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - phpenv config-rm xdebug.ini || true

install: composer update --prefer-dist --no-interaction --optimize-autoloader

script:
    - phpunit --exclude-group infra
    - if [[ "$CHECK_PHP_SYNTAX" == "yes" ]]; then vendor/bin/php-cs-fixer fix --config-file=.php_cs --dry-run --no-interaction --diff; fi;
